os: osx
osx_image: xcode7.3
language: cpp

compiler:
- clang
- gcc

script:
- xcodebuild -alltargets -configuration Debug -project ./Builds/MacOSX/Temper.xcodeproj/
- xcodebuild -alltargets -configuration Release -project ./Builds/MacOSX/Temper.xcodeproj/
- xcodebuild -alltargets -configuration Demo -project ./Builds/MacOSX/Temper.xcodeproj/

deploy:
  provider: s3
  access_key_id: AKIAJCWZQWRGWDG335JA
  secret_access_key:
    secure: KnCQH53mL5+oSG7nywdzpMsj+haMAnY92e3xnpCnMOgqkwkWtNE2ZIfhgcmo/7aKA202l0Puz4C55no4VCSwFEP7uU7xrUFGXWCgRoOxFHEiFQsE+djbHPJOCJ83wvb+XnbXCjDIiVE17AN5Y4j+6i+Jp31mTtDmkCd3tCCNlTfSqN+bfcQowPU+dXagIjq2q0GBSLYwyqm+xzhbgHXoBFEcKD5vWigG1va/L9MhFqbEKtfur/ze290/MyZWqxjF2PRlU1CLKPwMpFugVu3pO2JWiyI9kvJLVFFD/K+FZ2rsSWoMgmCgW+95Gmmia7ADTdfKmcASdOySPlsT/xVpPD3/JoE+0qehk7Copl6mGm5dnNWHQdv24+IgYyc5FxmkE8ghQwQc+B5FQsB4T3TZvyosYPmY4uKKWSH5sWrz7Xq6bdJ4uKGCdDFYL6W01aCnKahV2abBkFehIIFRr5MRDOmq1xw6FDoCI0ynkcp4zScGn3+7RGJ+OKVlLjMGooVz0K6s+NQv8ZHDxeikkPG9Z2/Llx5OLYScK4rHs9UoRv4ho4dr1H7fsoTJjtBt81sZ4IEXtkwJC7GiNf6SYcG7eX8Cj2sBbBzr8gA/nLZs7Nix6982CIda0q7vuUQi4uhkHuzph17vFQWUtnZzJlHPWi4GLuMbEaWA5/HTTdHFDkQ=
  bucket: ci-temper
  upload-dir: $TRAVIS_TAG/Builds/MacOSX
  skip_cleanup: true
  local_dir: ./Builds/MacOSX/build
  on:
    tags: true
