os: osx
osx_image: xcode7.3
language: cpp

script:
- xcodebuild -alltargets -configuration Debug -project ./Builds/MacOSX/Temper.xcodeproj/
- xcodebuild -alltargets -configuration Release -project ./Builds/MacOSX/Temper.xcodeproj/
- xcodebuild -alltargets -configuration Demo -project ./Builds/MacOSX/Temper.xcodeproj/

deploy:
  provider: s3
  access_key_id: AKIAJCWZQWRGWDG335JA
  secret_access_key:
    secure: pUQxpogc+hTPDm9R7SymuYLnGkFLq7ing7KqPALpZZObKHzhWKptRFR6RBzgMclBWL/9hWCpL3SqAdGVv33yM+/WnkDg+NauzTTcZ/7JNmThQLcyv01eqHlgjWCTIVnEMrg75TfCEvHaje3FAOq0vrvmxSV7HxAI2PVDsoP3wbrjOIDk/jnGTSP5bth3xC2bi6kedekyFnlnnvxAEvPRIbidAzimLcY/BVwYdf0qfqiWm61c7Xe4ffxNu1NcFR9POZXpn/5kNCU2SoKzlOGDWOaJHf1Dbw6kZsTzUYtOjQnYlnrW+3ydMe1PCmyEMD+hFFPwmJeqNFpTwbQGOClM2es0B09ZSy7xqVsMUBuB5neZdq5SNxid/dRVHXJQHaDoDOFtb6ZDvF8BrUaCv/DLRhOqgQaq1ROLPQAcoXBK+QIElEAtZl/yUN5xINDV2VkZCOPqfPho4xEnZo2KDJCKpqmaYnQ2GAywC34gWZuyXUgznOM2C/huxOFki0Ten1cAXIlDVkZJsCcRP3iCPdrQJfNrIrrVQYnewiJmt1Swf+a4OvBx+AMvMDXrND7YZlOrVmDR4HMhv7xVuz7pWWXnAGFYwMQVhHihT526aht1lDro39IUV9AIKCOWSRV6L/MEiagfd5cQQiQvBrA8OCU19l9Kzs5/WRUYVcJ9lzJSFEk=
  bucket: ci-temper
  skip_cleanup: true
  local-dir: "./Builds/MacOSX/build"
  upload-dir: "$TRAVIS_TAG/MacOSX"
  on:
    tags: true
    repo: creativeintent/temper
