#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# Fetch repository as zip archive
shallow_clone: true 

platform:
  - x86
  - x64

configuration:
  - Debug

matrix:
  fast_finish: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  parallel: true
  project: ./Builds/VisualStudio2015/mxzero.sln
  publish_wap: false
  publish_wap_xcopy: false
  publish_azure: false
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Builds/VisualStudio2015/Debug/mxzero.dll
  - path: Builds/VisualStudio2015/Debug/mxzero.vst3
