#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# Fetch repository as zip archive
shallow_clone: true 

platform:
 - Win32
 - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  parallel: true
  project: ./Builds/VisualStudio2015/mxzero.sln
  publish_wap: false
  publish_wap_xcopy: false
  publish_azure: false
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false

after_build:
  - cmd: copy Builds/VisualStudio2015/$(platform)/$(configuration)/mxzero.dll $(configuration)/mxzero\ $(platform).dll
  - cmd: copy Builds/VisualStudio2015/$(platform)/$(configuration)/mxzero.vst3 $(configuration)/mxzero\ $(platform).vst3

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: $(configuration)/mxzero\ $(platform).dll
  - path: $(configuration)/mxzero\ $(platform).vst3
#
#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: Environment
    name: mxzero
    on:
      appveyor_repo_tag: true
