#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# Fetch repository as zip archive
shallow_clone: true 

platform:
 - Win32
 - x64

configuration:
  - Debug
  - Release
  - Demo

matrix:
  fast_finish: false

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  parallel: true
  project: ./Builds/VisualStudio2017/Temper.sln
  publish_wap: false
  publish_wap_xcopy: false
  publish_azure: false
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Builds/VisualStudio2017/$(configuration)/*.dll
  - path: Builds/VisualStudio2017/$(configuration)/*.vst3
#
#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: Environment
    name: Temper
    on:
      appveyor_repo_tag: true
