#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# Fetch repository as zip archive
shallow_clone: true 

configuration:
  - Debug32
  - Debug64
  - Release32
  - Release64

matrix:
  fast_finish: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  parallel: true
  project: ./Builds/VisualStudio2015/mxzero.sln
  publish_wap: false
  publish_wap_xcopy: false
  publish_azure: false
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: false

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Builds/VisualStudio2015/$(platform)/$(configuration)/mxzero.dll
  - path: Builds/VisualStudio2015/$(platform)/$(configuration)/mxzero.vst3
